{% set version = "4.67.2" %}

package:
  name: tqdm
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/tqdm/tqdm-{{ version }}.tar.gz
  sha256: 649aac53964b2cb8dec76a14b405a4c0d13612cb8933aae547dd144eacc99653

build:
  noarch: python
  entry_points:
    - tqdm = tqdm.cli:main
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm >=3.4
    - toml
  run:
    - python >={{ python_min }}
    - colorama

test:
  requires:
    - pip
    - pytest
    - pytest-cov
    - pytest-timeout
    - pytest-asyncio >=0.24
    - python {{ python_min }}
  source_files:
    - tests
    - pyproject.toml
  imports:
    - tqdm
  commands:
    - pip check
    - tqdm --help
    - tqdm -v
    - pytest -k "not tests_perf and not tests_tk"

about:
  home: https://pypi.python.org/pypi/tqdm
  license: MPL-2.0 or MIT
  license_file: LICENCE
  summary: A Fast, Extensible Progress Meter
  dev_url: https://tqdm.github.io/docs/tqdm
  doc_url: https://github.com/tqdm/tqdm#tqdm
  doc_source_url: https://github.com/tqdm/tqdm/blob/master/README.rst

extra:
  recipe-maintainers:
    - casperdcl
    - pmlandwehr
    - synapticarbors
