{% set version = "4.62.2" %}

package:
  name: tqdm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tqdm/tqdm-{{ version }}.tar.gz
  sha256: a4d6d112e507ef98513ac119ead1159d286deab17dffedd96921412c2d236ff5

build:
  noarch: python
  entry_points:
    - tqdm = tqdm.cli:main
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2.7
    - pip
    - setuptools_scm >=3.4
    - toml
  run:
    - python >=2.7
    - colorama

test:
  requires:
    - pip
    - pytest
    - pytest-timeout
    - pytest-asyncio  # [py>=37]
  source_files:
    - tests
    - setup.cfg
    - pyproject.toml
  imports:
    - tqdm
  commands:
    - pip check
    - tqdm --help
    - tqdm -v
    - pytest -k "not tests_perf"

about:
  home: https://pypi.python.org/pypi/tqdm
  license: MPL-2.0 or MIT
  license_family: MOZILLA
  license_file: LICENCE
  summary: A Fast, Extensible Progress Meter
  dev_url: https://tqdm.github.io/docs/tqdm
  doc_url: https://github.com/tqdm/tqdm#tqdm
  doc_source_url: https://github.com/tqdm/tqdm/blob/master/README.rst

extra:
  recipe-maintainers:
    - casperdcl
    - pmlandwehr
