schema_version: 1

context:
  name: tqdm
  version: "4.68.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: c627124266fe7904cabb70e88a940d75a06b889a0b11680307a67c18ce094f19

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  python:
    entry_points:
      - tqdm = tqdm.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - setuptools_scm >=3.4
    - toml
  run:
    - python >=${{ python_min }}
    - if: win
      then:
        - colorama
        - __win
    - if: unix
      then: __unix

tests:
  - python:
      imports:
        - tqdm
      pip_check: true
      python_version: ${{ python_min }}.*
  - files:
      source:
        - tests
        - pyproject.toml
    requirements:
      run:
        - pytest
        - pytest-cov
        - pytest-timeout
        - pytest-asyncio >=0.24
        - python ${{ python_min }}.*
    script:
      - tqdm --help
      - tqdm -v
      - pytest -k "not perf and not tk"

about:
  license: MPL-2.0 and MIT
  license_file: LICENCE
  summary: A Fast, Extensible Progress Meter
  homepage: https://pypi.org/project/tqdm/
  repository: https://github.com/tqdm/tqdm
  documentation: https://tqdm.github.io

extra:
  recipe-maintainers:
    - casperdcl
    - pmlandwehr
    - synapticarbors
