schema_version: 1

context:
  version: 4.67.2

package:
  name: tqdm
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/tqdm/tqdm-${{ version }}.tar.gz
  sha256: 649aac53964b2cb8dec76a14b405a4c0d13612cb8933aae547dd144eacc99653

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  python:
    entry_points:
      - tqdm = tqdm.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - setuptools_scm >=3.4
    - toml
  run:
    - python >=${{ python_min }}
    - if: win
      then: 
        - colorama
        - __win
    - if: unix
      then: __unix

tests:
  - python:
      imports:
        - tqdm
      pip_check: true
      python_version: ${{ python_min }}.*
  - files:
      source:
        - tests
        - pyproject.toml
    requirements:
      run:
        - pytest
        - pytest-cov
        - pytest-timeout
        - pytest-asyncio >=0.24
        - python ${{ python_min }}.*
    script:
      - tqdm --help
      - tqdm -v
      - pytest -k "not perf and not tk"

about:
  license: MPL-2.0 and MIT
  license_file: LICENCE
  summary: A Fast, Extensible Progress Meter
  homepage: https://pypi.org/project/tqdm/
  repository: https://github.com/tqdm/tqdm
  documentation: https://tqdm.github.io

extra:
  recipe-maintainers:
    - casperdcl
    - pmlandwehr
    - synapticarbors
